class HashRing:
    def __init__(self, virtual_nodes: int=...):
        ...
    def add_node(self, name: str, weight: int=...) -> None:
        ...
    def remove_node(self, name: str) -> None:
        ...
    def get_node(self, key: str) -> str | None:
        ...
    def get_owners(self, keys: list[str]) -> list[str | None]:
        ...
    def get_replicas(self, key: str, count: int) -> list[str]:
        ...
    def __len__(self) -> int:
        ...
    def __contains__(self, name: str) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __getitem__(self, key: str) -> str:
        ...
    def __getnewargs__(self) -> tuple[int]:
        ...
    def __getstate__(self) -> list[tuple[str, int]]:
        ...
    def __setstate__(self, state: list[tuple[str, int]]) -> None:
        ...