from collections.abc import Iterator

class HashRing:
    def __init__(self, virtual_nodes: int = ...) -> None: ...
    def add_node(self, name: str, weight: int = ...) -> None: ...
    def remove_node(self, name: str) -> None: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def get_node(self, key: str) -> str | None: ...
    def __getitem__(self, key: str) -> str: ...
    def get_node_batch(self, keys: list[str]) -> list[str | None]: ...
    def get_replicas(self, key: str, count: int) -> list[str]: ...
    @property
    def nodes(self) -> dict[str, dict[str, int]]: ...
    def get_node_weight(self, name: str) -> int | None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getnewargs__(self) -> tuple[int]: ...
    def __getstate__(self) -> list[tuple[str, int]]: ...
    def __setstate__(self, state: list[tuple[str, int]]) -> None: ...
